/// Get metadata for an opcode
use super::*;
pub fn opcode_info(op: Opcode) -> OpcodeInfo {
    use super::Opcode::*;
    match op {
        // 0x00–0x0F: Stack
        Nop         => info("nop", 0, OpFlags::empty(), 0),
        PushNil     => info("push_nil", 0, OpFlags::empty(), 1),
        PushTrue    => info("push_true", 0, OpFlags::empty(), 1),
        PushFalse   => info("push_false", 0, OpFlags::empty(), 1),
        PushI32     => info("push_i32", 4, OpFlags::IMM32, 1),
        PushI64     => info("push_i64", 8, OpFlags::IMM64, 1),
        PushF32     => info("push_f32", 4, OpFlags::IMM32, 1),
        PushF64     => info("push_f64", 8, OpFlags::IMM64, 1),
        PushString  => info("push_string", 2, OpFlags::HAS_STRING, 1),
        PushConst   => info("push_const", 2, OpFlags::HAS_CONST, 1),
        Dup         => info("dup", 0, OpFlags::empty(), 1),
        DupN        => info("dup_n", 1, OpFlags::empty(), 0),
        Swap        => info("swap", 0, OpFlags::empty(), 0),
        Pop         => info("pop", 0, OpFlags::empty(), -1),
        PopN        => info("pop_n", 2, OpFlags::empty(), 0),
        Rot         => info("rot", 0, OpFlags::empty(), 0),

        // 0x10–0x1F: Integer Arith
        Add         => info("add", 0, OpFlags::empty(), -1),
        Sub         => info("sub", 0, OpFlags::empty(), -1),
        Mul         => info("mul", 0, OpFlags::empty(), -1),
        Div         => info("div", 0, OpFlags::empty(), -1),
        Mod         => info("mod", 0, OpFlags::empty(), -1),
        Neg         => info("neg", 0, OpFlags::empty(), 0),
        Inc         => info("inc", 0, OpFlags::empty(), 0),
        Dec         => info("dec", 0, OpFlags::empty(), 0),
        Abs         => info("abs", 0, OpFlags::empty(), 0),
        Pow         => info("pow", 0, OpFlags::empty(), -1),
        CheckedAdd  => info("checked_add", 0, OpFlags::empty(), -1),
        CheckedSub  => info("checked_sub", 0, OpFlags::empty(), -1),
        CheckedMul  => info("checked_mul", 0, OpFlags::empty(), -1),
        SaturatingAdd=>info("saturating_add", 0, OpFlags::empty(), -1),
        SaturatingSub=>info("saturating_sub", 0, OpFlags::empty(), -1),
        WrappingAdd => info("wrapping_add", 0, OpFlags::empty(), -1),

        // 0x20–0x2F: Float Arith
        FAdd        => info("f_add", 0, OpFlags::empty(), -1),
        FSub        => info("f_sub", 0, OpFlags::empty(), -1),
        FMul        => info("f_mul", 0, OpFlags::empty(), -1),
        FDiv        => info("f_div", 0, OpFlags::empty(), -1),
        FMod        => info("f_mod", 0, OpFlags::empty(), -1),
        FNeg        => info("f_neg", 0, OpFlags::empty(), 0),
        FPow        => info("f_pow", 0, OpFlags::empty(), -1),
        FSqrt       => info("f_sqrt", 0, OpFlags::empty(), 0),
        FAbs        => info("f_abs", 0, OpFlags::empty(), 0),
        FFloor      => info("f_floor", 0, OpFlags::empty(), 0),
        FCeil       => info("f_ceil", 0, OpFlags::empty(), 0),
        FRound      => info("f_round", 0, OpFlags::empty(), 0),
        FSin        => info("f_sin", 0, OpFlags::empty(), 0),
        FCos        => info("f_cos", 0, OpFlags::empty(), 0),
        FTan        => info("f_tan", 0, OpFlags::empty(), 0),
        FAtan2      => info("f_atan2", 0, OpFlags::empty(), -1),

        // 0x30–0x3F: Bitwise
        BitAnd      => info("bit_and", 0, OpFlags::empty(), -1),
        BitOr       => info("bit_or", 0, OpFlags::empty(), -1),
        BitXor      => info("bit_xor", 0, OpFlags::empty(), -1),
        BitNot      => info("bit_not", 0, OpFlags::empty(), 0),
        Shl         => info("shl", 0, OpFlags::empty(), -1),
        Shr         => info("shr", 0, OpFlags::empty(), -1),
        UShr        => info("u_shr", 0, OpFlags::empty(), -1),
        RotLeft     => info("rot_left", 0, OpFlags::empty(), -1),
        RotRight    => info("rot_right", 0, OpFlags::empty(), -1),
        PopCount    => info("pop_count", 0, OpFlags::empty(), 0),
        LeadingZeros=> info("leading_zeros", 0, OpFlags::empty(), 0),
        TrailingZeros=>info("trailing_zeros", 0, OpFlags::empty(), 0),
        ByteSwap    => info("byte_swap", 0, OpFlags::empty(), 0),
        BitReverse  => info("bit_reverse", 0, OpFlags::empty(), 0),
        UDiv        => info("u_div", 0, OpFlags::empty(), -1),
        UMod        => info("u_mod", 0, OpFlags::empty(), -1),

        // 0x40–0x4F: Compare & Logical
        Eq          => info("eq", 0, OpFlags::empty(), -1),
        Ne          => info("ne", 0, OpFlags::empty(), -1),
        Lt          => info("lt", 0, OpFlags::empty(), -1),
        Le          => info("le", 0, OpFlags::empty(), -1),
        Gt          => info("gt", 0, OpFlags::empty(), -1),
        Ge          => info("ge", 0, OpFlags::empty(), -1),
        Cmp         => info("cmp", 0, OpFlags::empty(), -1),
        Is          => info("is", 0, OpFlags::empty(), -1),
        IsNot       => info("is_not", 0, OpFlags::empty(), -1),
        In          => info("in", 0, OpFlags::empty(), -1),
        NotIn       => info("not_in", 0, OpFlags::empty(), -1),
        And         => info("and", 0, OpFlags::empty(), -1),
        Or          => info("or", 0, OpFlags::empty(), -1),
        Not         => info("not", 0, OpFlags::empty(), 0),
        Xor         => info("xor", 0, OpFlags::empty(), -1),
        Truthy      => info("truthy", 0, OpFlags::empty(), 0),

        // 0x50–0x5F: Type & Conversion
        TypeOf      => info("type_of", 0, OpFlags::empty(), 0),
        IsType      => info("is_type", 0, OpFlags::empty(), -1),
        ToI32       => info("to_i32", 0, OpFlags::empty(), 0),
        ToI64       => info("to_i64", 0, OpFlags::empty(), 0),
        ToF32       => info("to_f32", 0, OpFlags::empty(), 0),
        ToF64       => info("to_f64", 0, OpFlags::empty(), 0),
        ToBool      => info("to_bool", 0, OpFlags::empty(), 0),
        ToString    => info("to_string", 0, OpFlags::empty(), 0),
        Cast        => info("cast", 0, OpFlags::MAY_GC, 0),
        BitCast     => info("bit_cast", 0, OpFlags::empty(), 0),
        EnumCreate  => info("enum_create", 0, OpFlags::MAY_GC, -1),
        EnumMatch   => info("enum_match", 0, OpFlags::MAY_GC, -1),
        CheckIndex  => info("check_index", 0, OpFlags::empty(), -1),
        CheckType   => info("check_type", 0, OpFlags::empty(), 0),
        TypeAssert  => info("type_assert", 0, OpFlags::empty(), 0),
        Unreachable => info("unreachable", 0, OpFlags::TERMINATOR, 0),

        // 0x60–0x6F: Control Flow
        Jump        => info("jump", 2, OpFlags::IS_JUMP | OpFlags::TERMINATOR, 0),
        JumpIfFalse => info("jump_if_false", 2, OpFlags::IS_JUMP, -1),
        JumpIfTrue  => info("jump_if_true", 2, OpFlags::IS_JUMP, -1),
        JumpIfEq    => info("jump_if_eq", 2, OpFlags::IS_JUMP, -2),
        JumpIfNe    => info("jump_if_ne", 2, OpFlags::IS_JUMP, -2),
        JumpTable   => info("jump_table", 2, OpFlags::empty(), -1),
        ForPrep     => info("for_prep", 2, OpFlags::IS_JUMP, 0),
        ForStep     => info("for_step", 2, OpFlags::IS_JUMP, 0),
        Loop        => info("loop", 2, OpFlags::IS_JUMP | OpFlags::TERMINATOR, 0),
        Switch      => info("switch", 2, OpFlags::empty(), -1),
        MatchCheck  => info("match_check", 0, OpFlags::empty(), 0),
        Bind        => info("bind", 0, OpFlags::empty(), -1),
        GetIter     => info("get_iter", 0, OpFlags::MAY_GC, 0),
        Next        => info("next", 2, OpFlags::IS_JUMP | OpFlags::MAY_GC, -1),
        Await       => info("await", 0, OpFlags::MAY_GC, 0),
        AsyncCall   => info("async_call", 2, OpFlags::HAS_FUNC | OpFlags::MAY_GC, 0),

        // 0x70–0x7F: Call & Return
        Call        => info("call", 2, OpFlags::HAS_FUNC | OpFlags::MAY_GC, 0),
        CallValue   => info("call_value", 0, OpFlags::MAY_GC, 0),
        CallMethod  => info("call_method", 2, OpFlags::HAS_STRING | OpFlags::MAY_GC, 0),
        TailCall    => info("tail_call", 2, OpFlags::HAS_FUNC | OpFlags::TERMINATOR, 0),
        TailCallValue=>info("tail_call_value", 0, OpFlags::TERMINATOR, 0),
        Invoke      => info("invoke", 2, OpFlags::MAY_GC, 0),
        SuperCall   => info("super_call", 0, OpFlags::MAY_GC, 0),
        Apply       => info("apply", 0, OpFlags::MAY_GC, 0),
        Return      => info("return", 0, OpFlags::TERMINATOR, 0),
        ReturnValue => info("return_value", 0, OpFlags::TERMINATOR, -1),
        ReturnMultiple=>info("return_multiple", 1, OpFlags::TERMINATOR, 0),
        MakeClosure => info("make_closure", 2, OpFlags::HAS_FUNC | OpFlags::MAY_GC, 0),
        Capture     => info("capture", 0, OpFlags::empty(), -1),
        LoadUpvalue => info("load_upvalue", 1, OpFlags::empty(), 1),
        StoreUpvalue=> info("store_upvalue", 1, OpFlags::empty(), -1),
        Curry       => info("curry", 0, OpFlags::MAY_GC, 0),

        // 0x80–0x8F: Variables
        LoadLocal   => info("load_local", 2, OpFlags::HAS_LOCAL, 1),
        StoreLocal  => info("store_local", 2, OpFlags::HAS_LOCAL, -1),
        LoadCapture => info("load_capture", 1, OpFlags::empty(), 1),
        StoreCapture=> info("store_capture", 1, OpFlags::empty(), -1),
        LoadGlobal  => info("load_global", 2, OpFlags::HAS_GLOBAL, 1),
        StoreGlobal => info("store_global", 2, OpFlags::HAS_GLOBAL, -1),
        LoadDynGlobal=>info("load_dyn_global", 2, OpFlags::HAS_STRING, 1),
        StoreDynGlobal=>info("store_dyn_global", 2, OpFlags::HAS_STRING, -1),
        AllocFrame  => info("alloc_frame", 2, OpFlags::empty(), 0),
        LoadArg     => info("load_arg", 1, OpFlags::empty(), 1),
        LoadModuleVar=>info("load_module_var", 2, OpFlags::HAS_GLOBAL, 1),
        StoreModuleVar=>info("store_module_var", 2, OpFlags::HAS_GLOBAL, -1),
        LoadUpvalueFrom=>info("load_upvalue_from", 2, OpFlags::empty(), 1),
        StoreUpvalueTo=>info("store_upvalue_to", 2, OpFlags::empty(), -1),
        This        => info("this", 0, OpFlags::empty(), 1),
        ArgCount    => info("arg_count", 0, OpFlags::empty(), 1),

        // 0x90–0x9F: Array & List
        NewArray    => info("new_array", 2, OpFlags::MAY_GC, 0),
        ArrayLen    => info("array_len", 0, OpFlags::empty(), 0),
        ArrayGet    => info("array_get", 0, OpFlags::empty(), -1),
        ArraySet    => info("array_set", 0, OpFlags::empty(), -3),
        ArrayPush   => info("array_push", 0, OpFlags::empty(), -2),
        ArrayPop    => info("array_pop", 0, OpFlags::MAY_GC, 0),
        ArrayUnshift=> info("array_unshift", 0, OpFlags::empty(), -2),
        ArrayShift  => info("array_shift", 0, OpFlags::empty(), 0),
        ArrayInsert => info("array_insert", 0, OpFlags::empty(), -3),
        ArrayRemove => info("array_remove", 0, OpFlags::empty(), -2),
        ArraySlice  => info("array_slice", 0, OpFlags::MAY_GC, -1),
        ArrayConcat => info("array_concat", 0, OpFlags::MAY_GC, -1),
        ArrayContains=>info("array_contains", 0, OpFlags::empty(), -1),
        ArrayIndexOf=> info("array_index_of", 0, OpFlags::empty(), -1),
        ArraySort   => info("array_sort", 0, OpFlags::empty(), 0),
        ArrayReverse=> info("array_reverse", 0, OpFlags::empty(), 0),

        // 0xA0–0xAF: Map, Set, Range, Tuple
        NewMap      => info("new_map", 0, OpFlags::MAY_GC, 1),
        MapGet      => info("map_get", 0, OpFlags::empty(), -1),
        MapSet      => info("map_set", 0, OpFlags::MAY_GC, -3),
        MapDel      => info("map_del", 0, OpFlags::empty(), -2),
        MapContains => info("map_contains", 0, OpFlags::empty(), -1),
        MapKeys     => info("map_keys", 0, OpFlags::MAY_GC, 0),
        MapLen      => info("map_len", 0, OpFlags::empty(), 0),
        NewSet      => info("new_set", 0, OpFlags::MAY_GC, 1),
        SetAdd      => info("set_add", 0, OpFlags::empty(), -2),
        SetRemove   => info("set_remove", 0, OpFlags::empty(), -2),
        SetContains => info("set_contains", 0, OpFlags::empty(), -1),
        SetLen      => info("set_len", 0, OpFlags::empty(), 0),
        SetUnion    => info("set_union", 0, OpFlags::MAY_GC, -1),
        SetIntersect=> info("set_intersect", 0, OpFlags::MAY_GC, -1),
        NewRange    => info("new_range", 0, OpFlags::MAY_GC, -2),
        Tuple       => info("tuple", 2, OpFlags::MAY_GC, 0),

        // 0xB0–0xBF: String & Regex
        StrConcat   => info("str_concat", 0, OpFlags::MAY_GC, -1),
        StrLen      => info("str_len", 0, OpFlags::empty(), 0),
        StrGet      => info("str_get", 0, OpFlags::empty(), -1),
        StrSub      => info("str_sub", 0, OpFlags::MAY_GC, -2),
        StrContains => info("str_contains", 0, OpFlags::empty(), -1),
        StrIndexOf  => info("str_index_of", 0, OpFlags::empty(), -1),
        StrReplace  => info("str_replace", 0, OpFlags::MAY_GC, -3),
        StrSplit    => info("str_split", 0, OpFlags::MAY_GC, -1),
        StrJoin     => info("str_join", 0, OpFlags::MAY_GC, -1),
        StrToUpper  => info("str_to_upper", 0, OpFlags::MAY_GC, 0),
        StrToLower  => info("str_to_lower", 0, OpFlags::MAY_GC, 0),
        StrTrim     => info("str_trim", 0, OpFlags::MAY_GC, 0),
        StrCmp      => info("str_cmp", 0, OpFlags::empty(), -1),
        StrFormat   => info("str_format", 0, OpFlags::MAY_GC, 0),
        RegexCompile=> info("regex_compile", 0, OpFlags::MAY_GC, 0),
        RegexMatch  => info("regex_match", 0, OpFlags::empty(), -1),

        // 0xC0–0xCF: OOP
        NewNamespace=> info("new_namespace", 2, OpFlags::HAS_STRING | OpFlags::MAY_GC, 1),
        NewClass    => info("new_class", 0, OpFlags::MAY_GC, 1),
        NewObject   => info("new_object", 0, OpFlags::MAY_GC, 1),
        ClassAddMethod=>info("class_add_method", 2, OpFlags::HAS_STRING | OpFlags::MAY_GC, -1),
        ClassAddField=>info("class_add_field", 2, OpFlags::HAS_STRING, 0),
        ClassSetParent=>info("class_set_parent", 0, OpFlags::empty(), -1),
        GetAttr     => info("get_attr", 2, OpFlags::HAS_STRING | OpFlags::MAY_GC, 0),
        SetAttr     => info("set_attr", 2, OpFlags::HAS_STRING | OpFlags::MAY_GC, -2),
        HasAttr     => info("has_attr", 2, OpFlags::HAS_STRING, 0),
        InstanceOf  => info("instance_of", 0, OpFlags::empty(), -1),
        GetField    => info("get_field", 2, OpFlags::HAS_LOCAL, 0),
        SetField    => info("set_field", 2, OpFlags::HAS_LOCAL, -2),
        GetFieldIdx => info("get_field_idx", 2, OpFlags::HAS_LOCAL, 0),
        SetFieldIdx => info("set_field_idx", 2, OpFlags::HAS_LOCAL, -2),
        HasField    => info("has_field", 2, OpFlags::empty(), 0),
        InitStruct  => info("init_struct", 2, OpFlags::MAY_GC, 1),

        // 0xD0–0xDF: Functional & Coroutine
        Cons        => info("cons", 0, OpFlags::MAY_GC, -1),
        Car         => info("car", 0, OpFlags::empty(), 0),
        Cdr         => info("cdr", 0, OpFlags::empty(), 0),
        List        => info("list", 2, OpFlags::MAY_GC, 0),
        IsList      => info("is_list", 0, OpFlags::empty(), 0),
        MapFn       => info("map_fn", 0, OpFlags::MAY_GC, 0),
        FilterFn    => info("filter_fn", 0, OpFlags::MAY_GC, 0),
        ReduceFn    => info("reduce_fn", 0, OpFlags::MAY_GC, 0),
        Compose     => info("compose", 0, OpFlags::MAY_GC, 0),
        Delay       => info("delay", 0, OpFlags::MAY_GC, 0),
        Force       => info("force", 0, OpFlags::MAY_GC, 0),
        MakeCoroutine=>info("make_coroutine", 0, OpFlags::MAY_GC, 1),
        CoroutineStatus=>info("coroutine_status", 0, OpFlags::empty(), 0),
        CoroutineYield=>info("coroutine_yield", 0, OpFlags::empty(), 0),
        ResumeWith  => info("resume_with", 0, OpFlags::MAY_GC, 0),
        Continuation=> info("continuation", 0, OpFlags::MAY_GC, 0),

        // 0xE0–0xEF: CIB, Module, Plugin
        CibLoad     => info("cib_load", 0, OpFlags::empty(), 1),
        CibSym      => info("cib_sym", 0, OpFlags::empty(), 0),
        CibCall     => info("cib_call", 0, OpFlags::empty(), 0),
        CibWrap     => info("cib_wrap", 0, OpFlags::MAY_GC, 0),
        CibUnwrap   => info("cib_unwrap", 0, OpFlags::empty(), 0),
        CibFree     => info("cib_free", 0, OpFlags::empty(), -1),
        CibStrToC   => info("cib_str_to_c", 0, OpFlags::MAY_GC, 0),
        CibStrFromC => info("cib_str_from_c", 0, OpFlags::MAY_GC, 0),
        CibSizeOf   => info("cib_size_of", 0, OpFlags::empty(), 0),
        CibCallTyped=> info("cib_call_typed", 2, OpFlags::HAS_FUNC | OpFlags::MAY_GC, 0),
        CibLoadInterface=>info("cib_load_interface", 2, OpFlags::HAS_STRING, 1),
        CibStructPack=>info("cib_struct_pack", 0, OpFlags::MAY_GC, 0),
        Import      => info("import", 2, OpFlags::HAS_STRING | OpFlags::MAY_GC, 1),
        ImportFunc  => info("import_func", 2, OpFlags::HAS_STRING | OpFlags::MAY_GC, 0),
        ImportValue => info("import_value", 2, OpFlags::HAS_STRING, 0),
        Export      => info("export", 0, OpFlags::empty(), -1),

        // 0xF0–0xFF: GC, JIT, Debug
        Alloc       => info("alloc", 0, OpFlags::MAY_GC, 1),
        GcCollect   => info("gc_collect", 0, OpFlags::empty(), 0),
        GcPin       => info("gc_pin", 0, OpFlags::empty(), 0),
        GcUnpin     => info("gc_unpin", 0, OpFlags::empty(), 0),
        GcStats     => info("gc_stats", 0, OpFlags::empty(), 1),
        WriteBarrier=> info("write_barrier", 0, OpFlags::empty(), -1),
        GcSetThreshold=>info("gc_set_threshold", 0, OpFlags::empty(), -1),
        JitCompile  => info("jit_compile", 0, OpFlags::empty(), 0),
        JitInvalidate=>info("jit_invalidate", 0, OpFlags::empty(), 0),
        JitStat     => info("jit_stat", 0, OpFlags::empty(), 1),
        Print       => info("print", 0, OpFlags::empty(), -1),
        Trace       => info("trace", 0, OpFlags::empty(), 0),
        Breakpoint  => info("breakpoint", 0, OpFlags::empty(), 0),
        Line        => info("line", 2, OpFlags::empty(), 0),
        Halt        => info("halt", 0, OpFlags::TERMINATOR, 0),
        Raise       => info("raise", 0, OpFlags::TERMINATOR, -1),
    }
}

